version: "3.9"

services:
  post:
    build: "."
    command: "post-service"
    depends_on:
      - "postgres"
      - "nats"
    ports:
      - "8080"
    environment:
      POSTGRES_DB: "textboard"
      POSTGRES_USER: "poster"
      POSTGRES_PASSWORD: "qwerty"
      NATS_ADDRESS: "nats:4222"
  query:
    build: "."
    command: "query-service"
    depends_on:
      - "postgres"
      - "nats"
    ports:
      - "8080"
    environment:
      POSTGRES_DB: "textboard"
      POSTGRES_USER: "poster"
      POSTGRES_PASSWORD: "qwerty"
      NATS_ADDRESS: "nats:4222"
      ELASTICSEARCH_ADDRESS: "elasticsearch:9200"
  pusher:
    build: "."
    command: "pusher-service"
    depends_on:
      - "nats"
    ports:
      - "8080"
    environment:
      NATS_ADDRESS: "nats:4222"
  postgres:
    build: "./postgres"
    restart: "always"
    environment:
      POSTGRES_DB: "textboard"
      POSTGRES_USER: "poster"
      POSTGRES_PASSWORD: "qwerty"
  nats:
    image: "nats-streaming:latest"
    restart: "always"
  elasticsearch:
    image: "elasticsearch:8.4.3"
    ports:
      - "9200:9200"
    environment:
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms750m -Xmx750m"
      - "xpack.security.enabled=false"
  nginx:
    build: "./nginx"
    ports:
      - "8080:80"
    depends_on:
      - "post"
      - "query"
      - "pusher"