version: "3.9"

services:
  postgres:
    build: "./postgres"
    restart: "always"
    environment:
      POSTGRES_DB: "textboard"
      POSTGRES_USER: "poster"
      POSTGRES_PASSWORD: "qwerty"
  nats:
    image: "nats-streaming:latest"
    restart: "always"
  elasticsearch:
    image: "elasticsearch:8.4.3"
    ports:
      - "9200:9200"
    environment:
      - "discovery.type=single-node"